/******************************************************************************
* File Name: cycfg_gatt_db.c
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.80.0.1851
*
*******************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/******************************************************************************
* GATT server definitions
******************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GAP,
            __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_DEVICE_NAME,
                HDLC_GAP_DEVICE_NAME_VALUE,
                __UUID_CHARACTERISTIC_DEVICE_NAME,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_APPEARANCE,
                HDLC_GAP_APPEARANCE_VALUE,
                __UUID_CHARACTERISTIC_APPEARANCE,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: Peripheral Preferred Connection Parameters */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS,
                HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE,
                __UUID_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GATT,
            __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Immediate Alert */
    PRIMARY_SERVICE_UUID16 (
            HDLS_IAS,
            __UUID_SERVICE_IMMEDIATE_ALERT),
        /* Characteristic: Alert Level */
        CHARACTERISTIC_UUID16_WRITABLE (
                HDLC_IAS_ALERT_LEVEL,
                HDLC_IAS_ALERT_LEVEL_VALUE,
                __UUID_CHARACTERISTIC_ALERT_LEVEL,
                GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
                GATTDB_PERM_WRITE_CMD),

    /* Primary Service: Device Information */
    PRIMARY_SERVICE_UUID16 (
            HDLS_DIS,
            __UUID_SERVICE_DEVICE_INFORMATION),
        /* Characteristic: Manufacturer Name String */
        CHARACTERISTIC_UUID16 (
                HDLC_DIS_MANUFACTURER_NAME_STRING,
                HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE,
                __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: Firmware Revision String */
        CHARACTERISTIC_UUID16 (
                HDLC_DIS_FIRMWARE_REVISION_STRING,
                HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE,
                __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: PnP ID */
        CHARACTERISTIC_UUID16 (
                HDLC_DIS_PNP_ID,
                HDLC_DIS_PNP_ID_VALUE,
                __UUID_CHARACTERISTIC_PNP_ID,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),

    /* Primary Service: Scan Parameters */
    PRIMARY_SERVICE_UUID16 (
            HDLS_SCPS,
            __UUID_SERVICE_SCAN_PARAMETERS),
        /* Characteristic: Scan Interval Window */
        CHARACTERISTIC_UUID16_WRITABLE (
                HDLC_SCPS_SCAN_INTERVAL_WINDOW,
                HDLC_SCPS_SCAN_INTERVAL_WINDOW_VALUE,
                __UUID_CHARACTERISTIC_SCAN_INTERVAL_WINDOW,
                GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
                GATTDB_PERM_WRITE_CMD),

    /* Primary Service: Battery */
    PRIMARY_SERVICE_UUID16 (
            HDLS_BAS,
            __UUID_SERVICE_BATTERY),
        /* Characteristic: Battery Level */
        CHARACTERISTIC_UUID16 (
                HDLC_BAS_BATTERY_LEVEL,
                HDLC_BAS_BATTERY_LEVEL_VALUE,
                __UUID_CHARACTERISTIC_BATTERY_LEVEL,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
            /* Descriptor: Characteristic Presentation Format */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT,
                    GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD),

    /* Primary Service: Human Interface Device */
    PRIMARY_SERVICE_UUID16 (
            HDLS_HIDS,
            __UUID_SERVICE_HUMAN_INTERFACE_DEVICE),
        /* Included Service: Battery */
        INCLUDE_SERVICE_UUID16 (
                HDLI_HIDS_INCLUDE_BAS,
                HDLS_BAS,
                HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,
                __UUID_SERVICE_BATTERY),
        /* Characteristic: Report Map */
        CHARACTERISTIC_UUID16 (
                HDLC_HIDS_REPORT_MAP,
                HDLC_HIDS_REPORT_MAP_VALUE,
                __UUID_CHARACTERISTIC_REPORT_MAP,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE | GATTDB_PERM_AUTH_READABLE),
        /* Characteristic: gameControlller_report */
        CHARACTERISTIC_UUID16 (
                HDLC_HIDS_GAMECONTROLLLER_REPORT,
                HDLC_HIDS_GAMECONTROLLLER_REPORT_VALUE,
                __UUID_CHARACTERISTIC_REPORT,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_READABLE | GATTDB_PERM_AUTH_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_HIDS_GAMECONTROLLLER_REPORT_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
            /* Descriptor: Report Reference */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_HIDS_GAMECONTROLLLER_REPORT_REPORT_REFERENCE,
                    __UUID_DESCRIPTOR_REPORT_REFERENCE,
                    GATTDB_PERM_READABLE),
        /* Characteristic: HID Information */
        CHARACTERISTIC_UUID16 (
                HDLC_HIDS_HID_INFORMATION,
                HDLC_HIDS_HID_INFORMATION_VALUE,
                __UUID_CHARACTERISTIC_HID_INFORMATION,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: HID Control Point */
        CHARACTERISTIC_UUID16_WRITABLE (
                HDLC_HIDS_HID_CONTROL_POINT,
                HDLC_HIDS_HID_CONTROL_POINT_VALUE,
                __UUID_CHARACTERISTIC_HID_CONTROL_POINT,
                GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
                GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD),
        /* Characteristic: Protocol Mode */
        CHARACTERISTIC_UUID16_WRITABLE (
                HDLC_HIDS_PROTOCOL_MODE,
                HDLC_HIDS_PROTOCOL_MODE_VALUE,
                __UUID_CHARACTERISTIC_PROTOCOL_MODE,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
                GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/******************************************************************************
* GATT Initial Value Arrays
******************************************************************************/
 
uint8_t app_gap_device_name[] = {'X', 'E', 'N', 'S', 'I', 'V', ' ', 'G', 'a', 'm', 'e', 'p',
    'a', 'd', '\0',};
uint8_t app_gap_appearance[] = {0xC4, 0x03,};
uint8_t app_gap_peripheral_preferred_connection_parameters[] = {0x06, 0x00, 0x09, 0x00, 0x1E,
    0x00, 0x2C, 0x01,};
uint8_t app_ias_alert_level[] = {0x00,};
uint8_t app_dis_manufacturer_name_string[] = {'I', 'n', 'f', 'i', 'n', 'e', 'o', 'n', ' ', 'T',
    'e', 'c', 'h', 'n', 'o', 'l', 'o', 'g', 'i', 'e', 's',};
uint8_t app_dis_firmware_revision_string[] = {'1', '.', '0', '0',};
uint8_t app_dis_pnp_id[] = {0x01, 0x09, 0x00, 0x15, 0x08, 0x01, 0x00,};
uint8_t app_scps_scan_interval_window[] = {0x60, 0x00, 0x14, 0x00,};
uint8_t app_bas_battery_level[] = {0x00,};
uint8_t app_bas_battery_level_char_presentation_format[] = {0x04, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x00,};
uint8_t app_bas_battery_level_client_char_config[] = {0x00, 0x00,};
uint8_t app_hids_report_map[] = {
    /* USAGE_PAGE: Generic Desktop Controls */
    APP_HIDS_REPORT_MAP_USAGE_PAGE_0, APP_HIDS_REPORT_MAP_USAGE_PAGE_0_VALUE,
    /* USAGE: Game Pad */
    APP_HIDS_REPORT_MAP_USAGE_0, APP_HIDS_REPORT_MAP_USAGE_0_VALUE,
    /* COLLECTION: Application */
    APP_HIDS_REPORT_MAP_COLLECTION_0, APP_HIDS_REPORT_MAP_COLLECTION_0_VALUE,
    /* USAGE: Game Pad */
    APP_HIDS_REPORT_MAP_USAGE_1, APP_HIDS_REPORT_MAP_USAGE_1_VALUE,
    /* COLLECTION: Physical */
    APP_HIDS_REPORT_MAP_COLLECTION_1, APP_HIDS_REPORT_MAP_COLLECTION_1_VALUE,
    /* USAGE_PAGE: Button */
    APP_HIDS_REPORT_MAP_USAGE_PAGE_1, APP_HIDS_REPORT_MAP_USAGE_PAGE_1_VALUE,
    /* USAGE_MINIMUM: 0 */
    APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0, APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0_VALUE,
    /* USAGE_MAXIMUM: 0 */
    APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0, APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0_VALUE,
    /* LOGICAL_MINIMUM: 0 */
    APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0, APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0_VALUE,
    /* LOGICAL_MAXIMUM: 0 */
    APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0, APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0_VALUE,
    /* REPORT_SIZE: 0 */
    APP_HIDS_REPORT_MAP_REPORT_SIZE_0, APP_HIDS_REPORT_MAP_REPORT_SIZE_0_VALUE,
    /* REPORT_COUNT: 0 */
    APP_HIDS_REPORT_MAP_REPORT_COUNT_0, APP_HIDS_REPORT_MAP_REPORT_COUNT_0_VALUE,
    /* INPUT: 0 */
    APP_HIDS_REPORT_MAP_INPUT_0, APP_HIDS_REPORT_MAP_INPUT_0_VALUE,
    /* USAGE_PAGE: Generic Desktop Controls */
    APP_HIDS_REPORT_MAP_USAGE_PAGE_2, APP_HIDS_REPORT_MAP_USAGE_PAGE_2_VALUE,
    /* USAGE: X */
    APP_HIDS_REPORT_MAP_USAGE_2, APP_HIDS_REPORT_MAP_USAGE_2_VALUE,
    /* USAGE: Y */
    APP_HIDS_REPORT_MAP_USAGE_3, APP_HIDS_REPORT_MAP_USAGE_3_VALUE,
    /* USAGE: Z */
    APP_HIDS_REPORT_MAP_USAGE_4, APP_HIDS_REPORT_MAP_USAGE_4_VALUE,
    /* USAGE: Rx */
    APP_HIDS_REPORT_MAP_USAGE_5, APP_HIDS_REPORT_MAP_USAGE_5_VALUE,
    /* LOGICAL_MINIMUM: 0 */
    APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1, APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1_VALUE,
    /* LOGICAL_MAXIMUM: 0 */
    APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1, APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1_VALUE,
    /* REPORT_SIZE: 0 */
    APP_HIDS_REPORT_MAP_REPORT_SIZE_1, APP_HIDS_REPORT_MAP_REPORT_SIZE_1_VALUE,
    /* REPORT_COUNT: 0 */
    APP_HIDS_REPORT_MAP_REPORT_COUNT_1, APP_HIDS_REPORT_MAP_REPORT_COUNT_1_VALUE,
    /* INPUT: 0 */
    APP_HIDS_REPORT_MAP_INPUT_1, APP_HIDS_REPORT_MAP_INPUT_1_VALUE,
    /* END_COLLECTION */
    APP_HIDS_REPORT_MAP_END_COLLECTION_0,
    /* END_COLLECTION */
    APP_HIDS_REPORT_MAP_END_COLLECTION_1,};
uint8_t app_hids_gamecontrolller_report[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00,};
uint8_t app_hids_gamecontrolller_report_client_char_config[] = {0x00, 0x00,};
uint8_t app_hids_gamecontrolller_report_report_reference[] = {0x00, 0x01,};
uint8_t app_hids_hid_information[] = {0x01, 0x01, 0x00, 0x02,};
uint8_t app_hids_hid_control_point[] = {0x00,};
uint8_t app_hids_protocol_mode[] = {0x01,};
 
/******************************************************************************
* GATT Lookup Table
******************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    {
        HDLC_GAP_DEVICE_NAME_VALUE,                          /* attribute handle */
        14,                                                  /* maxlen */
        14,                                                  /* curlen */
        app_gap_device_name,                                 /* attribute data */
    },
    {
        HDLC_GAP_APPEARANCE_VALUE,                           /* attribute handle */
        2,                                                   /* maxlen */
        2,                                                   /* curlen */
        app_gap_appearance,                                  /* attribute data */
    },
    {
        HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE,/* attribute handle */
        8,                                                   /* maxlen */
        8,                                                   /* curlen */
        app_gap_peripheral_preferred_connection_parameters,  /* attribute data */
    },
    {
        HDLC_IAS_ALERT_LEVEL_VALUE,                          /* attribute handle */
        1,                                                   /* maxlen */
        1,                                                   /* curlen */
        app_ias_alert_level,                                 /* attribute data */
    },
    {
        HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE,             /* attribute handle */
        21,                                                  /* maxlen */
        21,                                                  /* curlen */
        app_dis_manufacturer_name_string,                    /* attribute data */
    },
    {
        HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE,             /* attribute handle */
        4,                                                   /* maxlen */
        4,                                                   /* curlen */
        app_dis_firmware_revision_string,                    /* attribute data */
    },
    {
        HDLC_DIS_PNP_ID_VALUE,                               /* attribute handle */
        7,                                                   /* maxlen */
        7,                                                   /* curlen */
        app_dis_pnp_id,                                      /* attribute data */
    },
    {
        HDLC_SCPS_SCAN_INTERVAL_WINDOW_VALUE,                /* attribute handle */
        4,                                                   /* maxlen */
        4,                                                   /* curlen */
        app_scps_scan_interval_window,                       /* attribute data */
    },
    {
        HDLC_BAS_BATTERY_LEVEL_VALUE,                        /* attribute handle */
        1,                                                   /* maxlen */
        1,                                                   /* curlen */
        app_bas_battery_level,                               /* attribute data */
    },
    {
        HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,     /* attribute handle */
        7,                                                   /* maxlen */
        7,                                                   /* curlen */
        app_bas_battery_level_char_presentation_format,      /* attribute data */
    },
    {
        HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,           /* attribute handle */
        2,                                                   /* maxlen */
        2,                                                   /* curlen */
        app_bas_battery_level_client_char_config,            /* attribute data */
    },
    {
        HDLC_HIDS_REPORT_MAP_VALUE,                          /* attribute handle */
        48,                                                  /* maxlen */
        48,                                                  /* curlen */
        app_hids_report_map,                                 /* attribute data */
    },
    {
        HDLC_HIDS_GAMECONTROLLLER_REPORT_VALUE,              /* attribute handle */
        6,                                                   /* maxlen */
        6,                                                   /* curlen */
        app_hids_gamecontrolller_report,                     /* attribute data */
    },
    {
        HDLD_HIDS_GAMECONTROLLLER_REPORT_CLIENT_CHAR_CONFIG, /* attribute handle */
        2,                                                   /* maxlen */
        2,                                                   /* curlen */
        app_hids_gamecontrolller_report_client_char_config,  /* attribute data */
    },
    {
        HDLD_HIDS_GAMECONTROLLLER_REPORT_REPORT_REFERENCE,   /* attribute handle */
        2,                                                   /* maxlen */
        2,                                                   /* curlen */
        app_hids_gamecontrolller_report_report_reference,    /* attribute data */
    },
    {
        HDLC_HIDS_HID_INFORMATION_VALUE,                     /* attribute handle */
        4,                                                   /* maxlen */
        4,                                                   /* curlen */
        app_hids_hid_information,                            /* attribute data */
    },
    {
        HDLC_HIDS_HID_CONTROL_POINT_VALUE,                   /* attribute handle */
        1,                                                   /* maxlen */
        1,                                                   /* curlen */
        app_hids_hid_control_point,                          /* attribute data */
    },
    {
        HDLC_HIDS_PROTOCOL_MODE_VALUE,                       /* attribute handle */
        1,                                                   /* maxlen */
        1,                                                   /* curlen */
        app_hids_protocol_mode,                              /* attribute data */
    },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = 
    (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = 14;
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_gap_peripheral_preferred_connection_parameters_len =
    (sizeof(app_gap_peripheral_preferred_connection_parameters));
const uint16_t app_ias_alert_level_len = (sizeof(app_ias_alert_level));
const uint16_t app_dis_manufacturer_name_string_len =
    (sizeof(app_dis_manufacturer_name_string));
const uint16_t app_dis_firmware_revision_string_len =
    (sizeof(app_dis_firmware_revision_string));
const uint16_t app_dis_pnp_id_len = (sizeof(app_dis_pnp_id));
const uint16_t app_scps_scan_interval_window_len = (sizeof(app_scps_scan_interval_window));
const uint16_t app_bas_battery_level_len = (sizeof(app_bas_battery_level));
const uint16_t app_bas_battery_level_char_presentation_format_len =
    (sizeof(app_bas_battery_level_char_presentation_format));
const uint16_t app_bas_battery_level_client_char_config_len =
    (sizeof(app_bas_battery_level_client_char_config));
const uint16_t app_hids_report_map_len = (sizeof(app_hids_report_map));
const uint16_t app_hids_gamecontrolller_report_len = (sizeof(app_hids_gamecontrolller_report));
const uint16_t app_hids_gamecontrolller_report_client_char_config_len =
    (sizeof(app_hids_gamecontrolller_report_client_char_config));
const uint16_t app_hids_gamecontrolller_report_report_reference_len =
    (sizeof(app_hids_gamecontrolller_report_report_reference));
const uint16_t app_hids_hid_information_len = (sizeof(app_hids_hid_information));
const uint16_t app_hids_hid_control_point_len = (sizeof(app_hids_hid_control_point));
const uint16_t app_hids_protocol_mode_len = (sizeof(app_hids_protocol_mode));
