/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.80.0.1851
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

/* Device address */
wiced_bt_device_address_t cy_bt_device_address = {0x00, 0xA0, 0x50, 0x57, 0xBB, 0xAD};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x05 };
const uint8_t cy_bt_adv_packet_elem_1[14] = { 0x58, 0x45, 0x4E, 0x53, 0x49, 0x56, 0x20, 0x47, 0x61, 0x6D, 0x65, 0x70, 0x61, 0x64 };
const uint8_t cy_bt_adv_packet_elem_2[2] = { 0x12, 0x18 };
const uint8_t cy_bt_adv_packet_elem_3[2] = { 0xC4, 0x03 };
wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] = 
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, 
    },
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 14, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, 
    },
    /* Incomplete list of 16-bit UUIDs available */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_16SRV_PARTIAL, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_2, 
    },
    /* Appearance */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_APPEARANCE, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_3, 
    },
};
