/***************************************************************************//**
* File Name: cycfg_gatt_db.h
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.80.0.1851
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                          0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                      0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                       0x2A01
#define __UUID_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS    0x2A04
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                       0x1801
#define __UUID_SERVICE_IMMEDIATE_ALERT                         0x1802
#define __UUID_CHARACTERISTIC_ALERT_LEVEL                      0x2A06
#define __UUID_SERVICE_DEVICE_INFORMATION                      0x180A
#define __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING         0x2A29
#define __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING         0x2A26
#define __UUID_CHARACTERISTIC_PNP_ID                           0x2A50
#define __UUID_SERVICE_SCAN_PARAMETERS                         0x1813
#define __UUID_CHARACTERISTIC_SCAN_INTERVAL_WINDOW             0x2A4F
#define __UUID_SERVICE_BATTERY                                 0x180F
#define __UUID_CHARACTERISTIC_BATTERY_LEVEL                    0x2A19
#define __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT    0x2904
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902
#define __UUID_SERVICE_HUMAN_INTERFACE_DEVICE                  0x1812
#define __UUID_CHARACTERISTIC_REPORT_MAP                       0x2A4B
#define __UUID_CHARACTERISTIC_REPORT                           0x2A4D
#define __UUID_DESCRIPTOR_REPORT_REFERENCE                     0x2908
#define __UUID_CHARACTERISTIC_HID_INFORMATION                  0x2A4A
#define __UUID_CHARACTERISTIC_HID_CONTROL_POINT                0x2A4C
#define __UUID_CHARACTERISTIC_PROTOCOL_MODE                    0x2A4E

/* Service Generic Access */
#define HDLS_GAP                                               0x0001
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                   0x0002
#define HDLC_GAP_DEVICE_NAME_VALUE                             0x0003
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                    0x0004
#define HDLC_GAP_APPEARANCE_VALUE                              0x0005
/* Characteristic Peripheral Preferred Connection Parameters */
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS    0x0006
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE    0x0007

/* Service Generic Attribute */
#define HDLS_GATT                                              0x0008

/* Service Immediate Alert */
#define HDLS_IAS                                               0x0009
/* Characteristic Alert Level */
#define HDLC_IAS_ALERT_LEVEL                                   0x000A
#define HDLC_IAS_ALERT_LEVEL_VALUE                             0x000B

/* Service Device Information */
#define HDLS_DIS                                               0x000C
/* Characteristic Manufacturer Name String */
#define HDLC_DIS_MANUFACTURER_NAME_STRING                      0x000D
#define HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE                0x000E
/* Characteristic Firmware Revision String */
#define HDLC_DIS_FIRMWARE_REVISION_STRING                      0x000F
#define HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE                0x0010
/* Characteristic PnP ID */
#define HDLC_DIS_PNP_ID                                        0x0011
#define HDLC_DIS_PNP_ID_VALUE                                  0x0012

/* Service Scan Parameters */
#define HDLS_SCPS                                              0x0013
/* Characteristic Scan Interval Window */
#define HDLC_SCPS_SCAN_INTERVAL_WINDOW                         0x0014
#define HDLC_SCPS_SCAN_INTERVAL_WINDOW_VALUE                   0x0015

/* Service Battery */
#define HDLS_BAS                                               0x0016
/* Characteristic Battery Level */
#define HDLC_BAS_BATTERY_LEVEL                                 0x0017
#define HDLC_BAS_BATTERY_LEVEL_VALUE                           0x0018
/* Descriptor Characteristic Presentation Format */
#define HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT        0x0019
/* Descriptor Client Characteristic Configuration */
#define HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG              0x001A

/* Service Human Interface Device */
#define HDLS_HIDS                                              0x001B
/* Service Battery */
#define HDLI_HIDS_INCLUDE_BAS                                  0x001C
/* Characteristic Report Map */
#define HDLC_HIDS_REPORT_MAP                                   0x001D
#define HDLC_HIDS_REPORT_MAP_VALUE                             0x001E
/* Characteristic gameControlller_report */
#define HDLC_HIDS_GAMECONTROLLLER_REPORT                       0x001F
#define HDLC_HIDS_GAMECONTROLLLER_REPORT_VALUE                 0x0020
/* Descriptor Client Characteristic Configuration */
#define HDLD_HIDS_GAMECONTROLLLER_REPORT_CLIENT_CHAR_CONFIG    0x0021
/* Descriptor Report Reference */
#define HDLD_HIDS_GAMECONTROLLLER_REPORT_REPORT_REFERENCE      0x0022
/* Characteristic HID Information */
#define HDLC_HIDS_HID_INFORMATION                              0x0023
#define HDLC_HIDS_HID_INFORMATION_VALUE                        0x0024
/* Characteristic HID Control Point */
#define HDLC_HIDS_HID_CONTROL_POINT                            0x0025
#define HDLC_HIDS_HID_CONTROL_POINT_VALUE                      0x0026
/* Characteristic Protocol Mode */
#define HDLC_HIDS_PROTOCOL_MODE                                0x0027
#define HDLC_HIDS_PROTOCOL_MODE_VALUE                          0x0028
/* HID Report Defines */
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_0                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_0_VALUE              0x01
#define APP_HIDS_REPORT_MAP_USAGE_0                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_0_VALUE                   0x05
#define APP_HIDS_REPORT_MAP_COLLECTION_0                    0xA1
#define APP_HIDS_REPORT_MAP_COLLECTION_0_VALUE              0x01
#define APP_HIDS_REPORT_MAP_USAGE_1                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_1_VALUE                   0x05
#define APP_HIDS_REPORT_MAP_COLLECTION_1                    0xA1
#define APP_HIDS_REPORT_MAP_COLLECTION_1_VALUE              0x00
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_1                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_1_VALUE              0x09
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0                 0x19
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0_VALUE           0x01
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0                 0x29
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0_VALUE           0x10
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0               0x15
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0_VALUE         0x00
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0               0x25
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0_VALUE         0x01
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_0                   0x75
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_0_VALUE             0x01
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_0                  0x95
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_0_VALUE            0x10
#define APP_HIDS_REPORT_MAP_INPUT_0                         0x81
#define APP_HIDS_REPORT_MAP_INPUT_0_VALUE                   0x02
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_2                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_2_VALUE              0x01
#define APP_HIDS_REPORT_MAP_USAGE_2                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_2_VALUE                   0x30
#define APP_HIDS_REPORT_MAP_USAGE_3                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_3_VALUE                   0x31
#define APP_HIDS_REPORT_MAP_USAGE_4                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_4_VALUE                   0x32
#define APP_HIDS_REPORT_MAP_USAGE_5                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_5_VALUE                   0x33
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1               0x15
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1_VALUE         0x81
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1               0x25
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1_VALUE         0x7F
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_1                   0x75
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_1_VALUE             0x08
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_1                  0x95
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_1_VALUE            0x04
#define APP_HIDS_REPORT_MAP_INPUT_1                         0x81
#define APP_HIDS_REPORT_MAP_INPUT_1_VALUE                   0x02
#define APP_HIDS_REPORT_MAP_END_COLLECTION_0                0xC0
#define APP_HIDS_REPORT_MAP_END_COLLECTION_1                0xC0

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_gap_peripheral_preferred_connection_parameters[];
extern const uint16_t app_gap_peripheral_preferred_connection_parameters_len;
extern uint8_t app_ias_alert_level[];
extern const uint16_t app_ias_alert_level_len;
extern uint8_t app_dis_manufacturer_name_string[];
extern const uint16_t app_dis_manufacturer_name_string_len;
extern uint8_t app_dis_firmware_revision_string[];
extern const uint16_t app_dis_firmware_revision_string_len;
extern uint8_t app_dis_pnp_id[];
extern const uint16_t app_dis_pnp_id_len;
extern uint8_t app_scps_scan_interval_window[];
extern const uint16_t app_scps_scan_interval_window_len;
extern uint8_t app_bas_battery_level[];
extern const uint16_t app_bas_battery_level_len;
extern uint8_t app_bas_battery_level_char_presentation_format[];
extern const uint16_t app_bas_battery_level_char_presentation_format_len;
extern uint8_t app_bas_battery_level_client_char_config[];
extern const uint16_t app_bas_battery_level_client_char_config_len;
extern uint8_t app_hids_report_map[];
extern const uint16_t app_hids_report_map_len;
extern uint8_t app_hids_gamecontrolller_report[];
extern const uint16_t app_hids_gamecontrolller_report_len;
extern uint8_t app_hids_gamecontrolller_report_client_char_config[];
extern const uint16_t app_hids_gamecontrolller_report_client_char_config_len;
extern uint8_t app_hids_gamecontrolller_report_report_reference[];
extern const uint16_t app_hids_gamecontrolller_report_report_reference_len;
extern uint8_t app_hids_hid_information[];
extern const uint16_t app_hids_hid_information_len;
extern uint8_t app_hids_hid_control_point[];
extern const uint16_t app_hids_hid_control_point_len;
extern uint8_t app_hids_protocol_mode[];
extern const uint16_t app_hids_protocol_mode_len;

#endif /* CYCFG_GATT_DB_H */
