/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V6.36.            *
*        Compiled Dec 18 2023, 11:48:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: arrow                                                 *
* Dimensions:  9 * 9                                                 *
* NumColors:   2                                                     *
* NumBytes:    58                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsarrow[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palarrow = {
  2,  // Number of entries
  0,  // No transparency
  (const LCD_COLOR *)&_Colorsarrow[0]
};

static GUI_CONST_STORAGE unsigned char _acarrow[] = {
  ____X___, ________,
  ___XX___, ________,
  __XXXXXX, X_______,
  _XXXXXXX, X_______,
  XXXXXXXX, X_______,
  _XXXXXXX, X_______,
  __XXXXXX, X_______,
  ___XX___, ________,
  ____X___, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmarrowLeft = {
  9, // xSize
  9, // ySize
  2, // BytesPerLine
  1, // BitsPerPixel
  (const unsigned char *)_acarrow,  // Pointer to picture data (indices)
  &_Palarrow,  // Pointer to palette
  NULL
};

/*************************** End of file ****************************/
