/*********************************************************************
*            (c) 1998 - 2023 SEGGER Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V6.36.            *
*        Compiled Dec 18 2023, 11:48:17                              *
*                                                                    *
*        (c) 1998 - 2023 SEGGER Microcontroller GmbH                 *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: gameControllerIcon                                    *
* Dimensions:  30 * 30                                               *
* NumColors:   2                                                     *
* NumBytes:    160                                                   *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#include "gameControllerIcon.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsgameControllerIcon[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalgameControllerIcon = {
  2,  // Number of entries
  0,  // No transparency
  (const LCD_COLOR *)&_ColorsgameControllerIcon[0]
};

static GUI_CONST_STORAGE unsigned char _acgameControllerIcon[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ______XX, XX______, ____XXXX, ________,
  _____XXX, XXX_____, ___XXXXX, X_______,
  ____XX__, ___XXXXX, XXX_____, XX______,
  ____X___, ________, ________, _X______,
  ___XX___, ________, ________, _XX_____,
  ___X____, _X______, ___XXX__, __X_____,
  ___X____, _X______, ___XX___, __X_____,
  ___X___X, XXXXX___, _XX__XXX, __X_____,
  __XX___X, XXXXX___, _XX__XXX, __XX____,
  __XX____, _X______, ___XX___, __XX____,
  __X_____, _X______, ___XXX__, ___X____,
  __X_____, ________, ________, ___X____,
  __X_____, ________, ________, ___X____,
  _XX_____, ___XXXXX, XXX_____, ___XX___,
  _X______, ________, __XXX___, ____X___,
  _X______, XX______, ____XX__, ____X___,
  _X_____X, X_______, _____XX_, ____X___,
  _X___XX_, ________, ______XX, X___X___,
  _XXXXX__, ________, ________, XXXXX___,
  __XXX___, ________, ________, _XXX____,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmgameControllerIcon = {
  30, // xSize
  30, // ySize
  4, // BytesPerLine
  1, // BitsPerPixel
  (const unsigned char *)_acgameControllerIcon,  // Pointer to picture data (indices)
  &_PalgameControllerIcon,  // Pointer to palette
  NULL
};

/*************************** End of file ****************************/
